source "http://rubygems.org"
gem 'rest-core', '>=2.0'
gem 'rest-more', '>=2.0'
gem 'sinatra', '>=1.3.0'
gem 'nokogiri', '>=1.5.0'
gem 'slim', '>=1.2'
gem 'sass', '>=3.2'
gem 'json', '>=1.3'
gem 'coffee-script', '>=2.2'
gem 'execjs'
gem 'therubyracer'
